apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-backend-deployment
  namespace: bookstoreapp  
  labels:
    app: catalog-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-backend
  template:
    metadata:
      labels:
        app: catalog-backend
    spec:
      containers:
      - name: catalog-backend
        image: chaphe/backend-catalog-image:1.0
        ports:
        - containerPort: 8081
        env:
        - name: MYSQL_DB_HOST
          value: mysql-catalog-service
        - name: MYSQL_DB_PORT
          value: "3306"
        - name: MYSQL_DB_USERNAME
          value: root
        - name: MYSQL_DB_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-backend-service
  namespace: bookstoreapp  
spec:
  type: NodePort
  selector:
    app: catalog-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-frontend-deployment
  namespace: bookstoreapp   
  labels:
    app: catalog-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-frontend
  template:
    metadata:
      labels:
        app: catalog-frontend
    spec:
      containers:
      - name: catalog-frontend
        image: chaphe/frontend-catalog-image:1.0
        ports:
        - containerPort: 80
        env:
        - name: CATALOG_URL
          value: http://172.28.128.1:30300
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-frontend-service
  namespace: bookstoreapp  
spec:
  type: NodePort
  selector:
    app: catalog-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30301